[general]
import = ["~/.config/alacritty/themes/noctaliatheme.toml"]

# title = "Alacritty"
# dynamic_title = true
# decorations = "Full"       # "Full" | "None" | "Transparent" | "Buttonless"
# option_as_alt = "Both" # "OnlyLeft" | "OnlyRight" | "Both" | "None" # (macOS only)
# opacity = 1
# startup_mode = "Maximized" # "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"(macOS only)

[env]
EDITOR = "nvim"

[font]
normal = { family = "JetBrainsMono Nerd Font Propo", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 9.3
builtin_box_drawing = true

[cursor]
style = { shape = "Underline", blinking = "Always" }
blink_interval = 500

[mouse]
hide_when_typing = true
