# Screen saver
set -g lock-after-time 300 # 300 seconds -> 5min
set -g lock-command "/usr/bin/cmatrix -sr"

# Smooth scroll settings
#
# Speed: 0-1000 | lower = faster
set -g @smooth-scroll-speed "100"

# Easing mode: linear|sine|quad
set -g @smooth-scroll-easing "sine"

# Scroll line distance
set -g @smooth-scroll-normal "3"
set -g @smooth-scroll-halfpage ""  # Default: pane_height / 2
set -g @smooth-scroll-fullpage ""  # Default: pane_height

# Enable on mouse wheel scroll
set -g @smooth-scroll-mouse "true"

# FloaX - Floating panes in Tmux!
#
# M- means "hold Meta/Alt"
set -g @floax-bind '-n M-p'

# The default width and height of the floating pane
set -g @floax-width '85%'
set -g @floax-height '85%'

# The border color can be changed, these are the colors supported by Tmux:
# black, red, green, yellow, blue, magenta, cyan, white for the standard
# terminal colors; brightred, brightyellow and so on for the bright variants;
# colour0/color0 to colour255/color255 for the colors from the 256-color
# palette; default for the default color; or a hexadecimal RGB color such as #882244.
set -g @floax-border-color 'blue'

# The text color can also be changed, by default it's blue
# to distinguish from the main window
# Optional colors are as shown above in @floax-border-color
set -g @floax-text-color 'blue'

# By default when floax sees a change in session path
# it'll change the floating pane's path
# You can disable this by setting it to false
# You could also "cd -" when the pane is toggled to go back
set -g @floax-change-path 'false'

# The default session name of the floating pane is 'scratch'
# You can modify the session name with this option:
set -g @floax-session-name 'floax-session'

# Change the title of the floating window
# set -g @floax-title 'floax'
