#! /usr/bin/env bash

# NOTE: Load pre
source "$DINNO_ZSH_DIR/pre_load.zsh"

# NOTE: Plugins
plugins=(
  # NOTE: Global
  ssh
  ssh-agent
  urltools
  copyfile
  copypath
  # NOTE: External
  fzf-tab
  zsh-vi-mode
  you-should-use
  zsh-autosuggestions
  fast-syntax-highlighting
  # NOTE: languages & tools
  git
  nvm
  npm
  rust
  golang
  docker
  docker-compose
)

# NOTE: Plugin settings
# NOTE: Make ssh-agent lazy load
zstyle :omz:plugins:ssh-agent lazy yes

# NOTE: Defer nvm's load until use it to speed-up zsh startup
zstyle ':omz:plugins:nvm' lazy yes
# NOTE: Define extra commands that will also trigger nvm load
zstyle ':omz:plugins:nvm' lazy-cmd eslint prettier typescript biome
# NOTE: .nvmrc autoload
zstyle ':omz:plugins:nvm' autoload yes
zstyle ':omz:plugins:nvm' silent-autoload yes # optionally remove the output generated by NVM when autoloading

# NOTE: Enable add zsh hook
autoload -U add-zsh-hook

# NOTE: Autosuggestions accept
bindkey '^n' autosuggest-accept

# NOTE: Setup oh my zsh
sourcefiles "$ZSH/oh-my-zsh.sh"

# NOTE: after load hook
sourcefiles "$DINNO_ZSH_DIR/after_load.zsh"
